import 'package:flutter/material.dart';

class Cal3CR extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(20.0),
      color: Colors.blue[900],
      alignment: Alignment.center,
      child: Row(
        mainAxisAlignment:
            MainAxisAlignment.center, //Sıralanışı merkezden başlar.
        mainAxisSize: MainAxisSize.max,
        crossAxisAlignment: CrossAxisAlignment.center,
        textDirection: TextDirection.ltr, //yazı yönü
        verticalDirection: VerticalDirection.down,
        textBaseline: TextBaseline.alphabetic,
        children: [
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.yellow,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.yellow,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.yellow,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.yellow,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            textDirection: TextDirection.ltr,
            verticalDirection: VerticalDirection.down,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.yellow,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.red,
              ),
              Container(
                height: 30.0,
                width: 30.0,
                padding: EdgeInsets.all(10.0),
                margin: EdgeInsets.all(10.0),
                color: Colors.white,
              ),
            ],
          ),
        ],
      ),
    );
  }
}
